### ISSUE TITLE
ValueError: No decoy PSMs were detected.

### ISSUE THREAD

**Issue by daishavdw** [wfondrie/mokapot#18] opened 2021-03-09 04:52 UTC
I have loaded a file in the required format (these are the first few lines and the names of the columns). 
```
SpecId | Label | ScanNr | Peptide | Proteins
0 | 1 | 38422 | R.AEGSDVANAVLDGADC[Common Fixed:Carbamidomethy... | P14618
1 | 1 | 41542 | R.SNYLLNTTIAGVEEADVVLLVGTNPR.F | P28331
```
I am getting an error saying that there are no decoy PSMs, however, I know there are decoys. My label column has -1's in it. It loads the file in, but is not getting any further than that. I have looked through the documentation and can't seem to see what I could be missing. Any suggestions would be greatly appreciated. Thank you!

Here is the error that I am getting. 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-bc18f4fefa97> in <module>
----> 1 psms = mokapot.read_pin(file)
      2 results, models = mokapot.brew(psms)
      3 results.to_txt()

~/anaconda3/lib/python3.8/site-packages/mokapot/parsers.py in read_pin(pin_files, group_column, to_df, copy_data)
    103         return pin_df
    104 
--> 105     return LinearPsmDataset(
    106         psms=pin_df,
    107         target_column=labels[0],

~/anaconda3/lib/python3.8/site-packages/mokapot/dataset.py in __init__(self, psms, target_column, spectrum_columns, peptide_column, protein_column, group_column, feature_columns, copy_data)
    427             raise ValueError("No target PSMs were detected.")
    428         if not num_decoys:
--> 429             raise ValueError("No decoy PSMs were detected.")
    430         if not self.data.shape[0]:
    431             raise ValueError("No PSMs were detected.")

ValueError: No decoy PSMs were detected.
```

**Comment by wfondrie** [comment] 2021-03-09 06:38
Hi @daishavdw,

Thanks for trying mokapot. I have a couple questions about your input file:

1. Are those all of the columns in the file? If so, it looks like there are no features for mokapot to use.
2. Is the file is actually delimited by tabs (`\t`)? I'm guessing that you wrote `|` to make the columns easier to see, but I just wanted to verify. 

Thanks!

**Comment by daishavdw** [comment] 2021-03-09 17:36
Hi, thank you so much for your response. 
1. No, there are actually many more columns in the file, I just cut it down to show that it has the ones that the documentation in Mokapot asks for. 
2. Yes, the file is eliminated by tabs. It is actually a file that was specifically generated to be able to be run in Percolator. Looking at the documentation it looks like the input type is the same for Percolator and Mokapot, so I assume it would work. But if that is wrong please let me know.
Thank you.

**Comment by wfondrie** [comment] 2021-03-09 17:40
Great - thank you for the clarifications. 

Can you share either all or part of the file, with some decoy PSMs included? I can't reproduce the error with the sample above.

**Comment by daishavdw** [comment] 2021-03-11 18:17
Thank you so much for your help. 
The search engine we used was MetaMorpheus. They have a .tab output file that is meant for Percolator. 
While trying to break down the file to send you a smaller portion of it, I discovered that instead of reading in the .tab file, I needed to convert it to an excel file, read it back in, and then everything works.
Thank you so much for your help. It was very appreciated.

**Comment by wfondrie** [comment] 2021-03-11 19:09
I'm glad to hear it. It's odd though that the file didn't work directly. I'll see if I can find an example from the MetaMorpheus folks to test. 

I'll close the issue for now, but please re-open it if you have any more trouble.

**Closed by wfondrie** 2021-03-11 19:09 UTC

**Comment by daishavdw** [comment] 2021-03-11 20:20
Hi,
Ideally we would like to just run the file without having to convert back and forth. I have put the file and a Jupyter notebook on a GitHub repo, where I load the file and try to run it, so you can reproduce the errors.  

https://github.com/PayneLab/SingleCellBenchMark/tree/main/MokaPot

Thank you again.

**Comment by wfondrie** [comment] 2021-03-11 20:34
I've figured out the problem: The dtype of your `Label` column is `object`. Adding the following line fixes the issue:
```Python
df["Label"] = df["Label"].astype(int)
```

Ideally mokapot would handle this conversion automatically. I'll update this and it'll be available in the next release.

**Comment by daishavdw** [comment] 2021-03-11 20:35
Thank you so much for letting me know. I really appreciate all your help!

**Comment by wfondrie** [comment] 2021-03-11 20:35
Thank you for finding it and sharing your code!

**Comment by wfondrie** [comment] 2021-03-11 21:49
I just added this fix into the master branch. Additionally, I added support for ignoring the "DefaultDirection" line so that you shouldn't have to read it into DataFrame first. It'll be in the next release, but you can try it out now by installing the development version:
```
pip3 install git+git://github.com/wfondrie/mokapot
```
